# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=50)),
                ('fecha_consulta', models.DateTimeField()),
                ('doctor', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('Desconocido', 'Desconocido')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('especialidad', models.CharField(max_length=50)),
                ('horario_atencion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('rut', models.CharField(max_length=10)),
                ('seguro', models.CharField(choices=[('Fonasa', 'Fonasa')], max_length=20)),
                ('ranking', models.FloatField()),
                ('ficha', models.CharField(max_length=500)),
                ('telefono_contacto', models.CharField(max_length=10)),
                ('mail', models.CharField(max_length=10)),
                ('avisar_a', models.CharField(max_length=50)),
                ('via_de_contacto', models.CharField(choices=[('Mail', 'Mail'), ('Llamada', 'Llamada'), ('SMS', 'SMS')], max_length=20)),
            ],
        ),
    ]
