# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='fecha_consulta',
            new_name='fecha',
        ),
        migrations.AddField(
            model_name='consulta',
            name='duracion',
            field=models.PositiveSmallIntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Doctor'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Paciente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='mail',
            field=models.EmailField(max_length=10),
        ),
    ]
