# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 05:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160612_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='duracion',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
    ]
